'use client';

import { useEffect, useState } from 'react';
import { ChevronDown, ExternalLink, Instagram, MessageCircle, RefreshCw, Send, Youtube } from 'lucide-react';

type Platform = 'all' | 'instagram' | 'youtube';
type Post = { id: string; platform: 'instagram' | 'youtube'; accountId: string; accountUsername?: string; content?: string; picture?: string; permalink?: string; createdTime?: string; commentCount?: number };
type ThreadComment = { id: string; message?: string; createdTime?: string; platform?: string; from?: { name?: string; username?: string; picture?: string; isOwner?: boolean }; replies?: ThreadComment[] };
const icon = (platform: string) => platform === 'youtube' ? Youtube : Instagram;
const compact = (value?: string) => value && value.length > 98 ? `${value.slice(0, 98)}…` : value || 'Post sem texto';

export function CommentsWorkspace() {
  const [platform, setPlatform] = useState<Platform>('all');
  const [posts, setPosts] = useState<Post[]>([]); const [selected, setSelected] = useState<Post | null>(null); const [includeEmpty, setIncludeEmpty] = useState(false);
  const [comments, setComments] = useState<ThreadComment[]>([]); const [loadingPosts, setLoadingPosts] = useState(true); const [loadingThread, setLoadingThread] = useState(false);
  const [error, setError] = useState<string | null>(null); const [draft, setDraft] = useState(''); const [sending, setSending] = useState(false);

  const loadPosts = async () => { setLoadingPosts(true); setError(null); const query = new URLSearchParams(); if (platform !== 'all') query.set('platform', platform); if (includeEmpty) query.set('includeEmpty', 'true'); const response = await fetch(`/api/comments/posts${query.size ? `?${query}` : ''}`); const data = await response.json().catch(() => ({})); if (!response.ok) { setError(data.message ?? 'Não foi possível carregar os posts.'); setPosts([]); } else { const next = data.posts ?? []; setPosts(next); setSelected((current) => next.find((post: Post) => post.id === current?.id) ?? next[0] ?? null); } setLoadingPosts(false); };
  useEffect(() => { void loadPosts(); }, [platform, includeEmpty]);
  useEffect(() => { if (!selected) { setComments([]); return; } const load = async () => { setLoadingThread(true); setError(null); const response = await fetch(`/api/comments/posts/${encodeURIComponent(selected.id)}?accountId=${encodeURIComponent(selected.accountId)}`); const data = await response.json().catch(() => ({})); if (!response.ok) { setError(data.message ?? 'Não foi possível carregar os comentários.'); setComments([]); } else setComments(data.comments ?? []); setLoadingThread(false); }; void load(); }, [selected]);
  const reply = async () => { if (!selected || !draft.trim() || !comments[0]) return; setSending(true); const response = await fetch('/api/comments/reply', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ postId: selected.id, commentId: comments[0].id, accountId: selected.accountId, message: draft.trim() }) }); const data = await response.json().catch(() => ({})); setSending(false); if (!response.ok) { setError(data.message ?? 'Não foi possível enviar a resposta.'); return; } setDraft(''); const refreshed = await fetch(`/api/comments/posts/${encodeURIComponent(selected.id)}?accountId=${encodeURIComponent(selected.accountId)}`); const thread = await refreshed.json().catch(() => ({})); setComments(thread.comments ?? comments); };
  return <div className="flex h-[calc(100vh-4rem)] min-h-[650px] overflow-hidden bg-[#111827] text-slate-100">
    <aside className="flex w-[38%] min-w-[350px] max-w-[560px] flex-col border-r border-slate-700 bg-[#111827]">
      <div className="border-b border-slate-700 p-4"><h1 className="text-xl font-bold">Comentários</h1><div className="mt-3 flex items-center gap-2"><label className="relative"><select aria-label="Filtrar plataforma" value={platform} onChange={(event) => setPlatform(event.target.value as Platform)} className="appearance-none rounded-md border border-slate-600 bg-[#161d2b] py-2 pl-3 pr-8 text-sm text-slate-100"><option value="all">Todas as plataformas</option><option value="instagram">Instagram</option><option value="youtube">YouTube</option></select><ChevronDown className="pointer-events-none absolute right-2 top-2.5 h-4 w-4" /></label><button onClick={() => void loadPosts()} className="rounded-md border border-slate-600 p-2 hover:bg-slate-800" title="Atualizar"><RefreshCw className={loadingPosts ? 'h-4 w-4 animate-spin' : 'h-4 w-4'} /></button></div><label className="mt-3 flex cursor-pointer items-center gap-2 text-xs text-slate-400"><input type="checkbox" checked={includeEmpty} onChange={(event) => setIncludeEmpty(event.target.checked)} className="accent-orange-600" /> Incluir posts sem comentários</label></div>
      <div className="flex-1 overflow-y-auto">{posts.map((post) => { const Icon = icon(post.platform); const active = selected?.id === post.id; return <button key={`${post.platform}-${post.id}`} onClick={() => setSelected(post)} className={`flex w-full gap-3 border-b border-slate-800 p-3 text-left transition ${active ? 'bg-slate-700/70' : 'hover:bg-slate-800/70'}`}><div className="h-14 w-14 shrink-0 overflow-hidden rounded bg-slate-700">{post.picture ? <img src={post.picture} alt="" className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center"><Icon className="h-5 w-5" /></div>}</div><div className="min-w-0 flex-1"><p className="line-clamp-2 text-sm font-semibold leading-5">{compact(post.content)}</p><div className="mt-1 flex items-center gap-1 text-xs text-slate-400"><Icon className="h-3.5 w-3.5" /> @{post.accountUsername} <span className="ml-2 inline-flex items-center gap-1"><MessageCircle className="h-3.5 w-3.5" /> {post.commentCount ?? 0}</span></div></div></button>; })}{!loadingPosts && posts.length === 0 && <p className="p-6 text-center text-sm text-slate-400">Nenhum post encontrado para este filtro.</p>}</div>
    </aside>
    <main className="flex min-w-0 flex-1 flex-col bg-[#171717]">{selected ? <><header className="flex items-center justify-between border-b border-slate-700 px-5 py-4"><div><h2 className="font-semibold">Comentários ({comments.length})</h2><p className="mt-1 line-clamp-1 text-xs text-slate-400">{selected.content}</p></div>{selected.permalink && <a href={selected.permalink} target="_blank" rel="noreferrer" className="text-slate-400 hover:text-white"><ExternalLink className="h-4 w-4" /></a>}</header><div className="flex-1 overflow-y-auto p-4 space-y-3">{loadingThread ? <p className="text-sm text-slate-400">Carregando comentários…</p> : comments.map((comment) => <CommentCard key={comment.id} comment={comment} platform={selected.platform} />)}{!loadingThread && comments.length === 0 && <p className="text-sm text-slate-400">Este post ainda não tem comentários.</p>}</div><div className="border-t border-slate-700 p-4"><div className="flex rounded-xl border border-slate-600 bg-[#111827] p-1"><input value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void reply(); } }} placeholder="Escreva um comentário..." className="min-w-0 flex-1 bg-transparent px-3 text-sm outline-none" /><button disabled={sending || !draft.trim() || comments.length === 0} onClick={() => void reply()} className="rounded-lg bg-orange-700 p-2 text-white disabled:opacity-40"><Send className="h-5 w-5" /></button></div></div></> : <div className="flex flex-1 items-center justify-center text-slate-400">Selecione um post para abrir a thread.</div>}</main>{error && <div className="fixed bottom-4 right-4 max-w-sm rounded-lg bg-red-600 px-4 py-3 text-sm text-white shadow-xl">{error}</div>}</div>;
}

function CommentCard({ comment, platform }: { comment: ThreadComment; platform: string }) { const Icon = icon(platform); const author = comment.from?.name ?? comment.from?.username ?? 'Usuário'; return <article className={`rounded-md border p-4 ${comment.from?.isOwner ? 'border-stone-300 bg-stone-100 text-stone-900' : 'border-slate-700 bg-[#252525]'}`}><div className="flex items-start gap-3">{comment.from?.picture ? <img src={comment.from.picture} alt="" className="h-9 w-9 rounded-full object-cover" /> : <div className="flex h-9 w-9 items-center justify-center rounded-full bg-slate-700"><Icon className="h-4 w-4" /></div>}<div className="min-w-0"><div className="font-semibold">{author} {comment.from?.isOwner && <span className="ml-1 rounded bg-amber-200 px-1.5 py-0.5 text-[10px] font-medium text-amber-900">Você</span>}</div><p className="mt-1 whitespace-pre-wrap text-sm leading-6">{comment.message || 'Comentário sem texto'}</p><time className="mt-2 block text-xs opacity-60">{comment.createdTime ? new Date(comment.createdTime).toLocaleString('pt-BR') : ''}</time></div></div></article>; }
